version: '3'
services:
  nginx:
    container_name: nginx
    image: vmeling/app-nginx:1.0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  web:
    image: vmeling/app-php:2.0
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/arch.homework
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
  postgres:
    container_name: db
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: my_user
      POSTGRESQL_PASSWORD: my_password
      POSTGRESQL_DATABASE: my_database
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 172.17.0.0/24