apiVersion: v1
kind: Service
metadata:
  name: {{include "user-chart.fullname" .}}
  labels:
    {{- include "user-chart.labels" . | nindent 4}}
spec:
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: 80
      protocol: TCP
  type: {{.Values.service.type}}